[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_fall_transfer_hook = "B6HgDmYT5oyin8EZEzK7UMCYF3BULjVeBYry6v839sYs"
token_mover = "GGEBzupdAvuzTQvgCq3G9itbAaN29HYHN6dqzxsHJyke"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
